# Generated by Django 2.0.4 on 2018-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('REAL_TIME_VERIFY', 'Real time verify'), ('OFFLINE_VERIFY', 'Offline verify'), ('DONE', 'Done')], default='REAL_TIME_VERIFY', max_length=30),
        ),
    ]
