# Generated by Django 2.0.4 on 2018-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180503_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.IntegerField(choices=[(1, 'Recycle'), (0, 'Non-recycle')], null=True),
        ),
        migrations.AlterField(
            model_name='imageprofile',
            name='type',
            field=models.IntegerField(choices=[(1, 'Recycle'), (0, 'Non-recycle')], null=True),
        ),
    ]
