# Generated by Django 2.0.4 on 2018-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180516_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.FileField(upload_to='img'),
        ),
    ]
