# Generated by Django 2.0.5 on 2018-05-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180517_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created', '-id')},
        ),
        migrations.AlterModelOptions(
            name='imageprofile',
            options={'ordering': ('-id',)},
        ),
    ]
