# Generated by Django 2.0.5 on 2018-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180518_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='type_ai',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
