# Generated by Django 2.0.5 on 2018-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180523_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bottle'), (1, 'Cans of metal'), (2, 'Newspapers, writing paper'), (3, 'Stories, magazines'), (4, 'Carton water box'), (5, 'Paper cup'), (6, 'Carton box, paper box'), (7, 'Metal tools'), (8, 'Bottle of water'), (9, 'Plastic bottle, glass'), (10, 'Plate, plastic'), (11, 'Spoons, forks, plastic knives'), (12, 'Plastic box'), (13, 'Silver foil'), (14, 'Paper bags'), (15, 'Plastic bags + plastic bags'), (16, 'Styrofoam'), (17, 'Ice cream'), (18, 'Battery'), (19, 'Others')], default=None, null=True),
        ),
    ]
