# Generated by Django 2.0.5 on 2018-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_imageprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
