# Generated by Django 2.0.5 on 2018-06-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180601_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
