# Generated by Django 2.0.5 on 2018-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20180601_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tx',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
