# Generated by Django 2.0.6 on 2018-06-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180601_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_categories',
            field=models.ManyToManyField(through='api.FollowedCategory', to='api.Category'),
        ),
    ]
