# Generated by Django 2.0.6 on 2018-06-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180606_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followedcategory',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterUniqueTogether(
            name='followedcategory',
            unique_together={('profile', 'category')},
        ),
    ]
