# Generated by Django 2.0.5 on 2018-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_categoryprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprofile',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
