# Generated by Django 2.0.6 on 2018-06-08 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180607_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('following_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_profile', to='api.Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='followingprofile',
            unique_together={('profile', 'following_profile')},
        ),
    ]
