# Generated by Django 2.0.5 on 2018-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180604_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprofile',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
