# Generated by Django 2.0.5 on 2018-06-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20180604_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryprofile',
            old_name='amount',
            new_name='balance',
        ),
    ]
