# Generated by Django 2.0.5 on 2018-06-08 04:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180604_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.FileField(upload_to=api.models.category_path),
        ),
    ]
