# Generated by Django 2.0.5 on 2018-06-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180608_0325'),
        ('api', '0041_auto_20180608_0438'),
    ]

    operations = [
    ]
