# Generated by Django 2.0.6 on 2018-06-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20180608_0438'),
        ('api', '0040_auto_20180608_0325'),
    ]

    operations = [
    ]
