# Generated by Django 2.0.6 on 2018-06-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180608_0918'),
        ('api', '0042_merge_20180608_0817'),
    ]

    operations = [
    ]
