# Generated by Django 2.0.6 on 2018-06-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180615_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeImage',
            new_name='LikedImage',
        ),
    ]
