# Generated by Django 2.0.7 on 2018-07-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180615_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprofile',
            name='tx',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_images',
            field=models.ManyToManyField(related_name='liked_images', through='api.LikedImage', to='api.Image'),
        ),
    ]
