# Generated by Django 2.0.7 on 2018-07-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180703_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryprofile',
            name='tx',
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='tx',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
