# Generated by Django 2.0.7 on 2018-07-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180704_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tx',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
