# Generated by Django 2.0.7 on 2018-07-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_image_tx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='created_by', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='request_eth_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='request_goal',
            field=models.IntegerField(null=True),
        ),
    ]
