# Generated by Django 2.0.7 on 2018-07-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180705_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.AddField(
            model_name='category',
            name='created_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='request_eth_amount',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='request_goal',
            field=models.IntegerField(default=0),
        ),
    ]
