# Generated by Django 2.0.7 on 2018-07-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20180712_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='buydataset',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
