# Generated by Django 2.0.7 on 2018-07-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_buydataset_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydataset',
            name='email',
        ),
    ]
