# Generated by Django 2.0.7 on 2018-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_category_init_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='request_eth_amount',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
