# Generated by Django 2.0.7 on 2018-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180727_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contract_addr',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
