# Generated by Django 2.0.7 on 2018-08-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_payhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='profile',
        ),
    ]
