# Generated by Django 2.0.7 on 2018-08-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_payhistory_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='tokens',
            field=models.CharField(max_length=255),
        ),
    ]
