# Generated by Django 2.0.7 on 2018-08-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180815_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='provider',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
