# Generated by Django 2.0.4 on 2018-04-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_wallet',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
