# Generated by Django 2.0.4 on 2018-04-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_address_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_wallet',
            field=models.CharField(max_length=255),
        ),
    ]
