# Generated by Django 2.0.4 on 2018-05-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.FileField(upload_to=''),
        ),
    ]
