# Generated by Django 2.0.4 on 2018-04-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180425_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_wallet',
            new_name='ether_address',
        ),
    ]
