# Generated by Django 2.0.4 on 2018-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180503_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.ImageField(upload_to='img'),
        ),
    ]
