# Generated by Django 2.0.4 on 2018-05-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180503_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('1', 'Recycle'), ('0', 'Non-recycle')], max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.IntegerField(choices=[('1', 'Recycle'), ('0', 'Non-recycle')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Image'),
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Profile'),
        ),
    ]
