# Generated by Django 2.0.4 on 2018-05-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180503_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('VERIFYING', 'Verifying'), ('DONE', 'Done')], default='VERIFYING', max_length=30),
        ),
    ]
