# Generated by Django 2.0.5 on 2018-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180522_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='type',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
