# Generated by Django 2.0.5 on 2018-05-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classify',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Classify'),
        ),
    ]
