# Generated by Django 2.0.5 on 2018-05-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_image_classify'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprofile',
            name='type',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Classify')], default=1),
        ),
    ]
