# Generated by Django 2.0.5 on 2018-05-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_classify_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageprofile',
            unique_together=set(),
        ),
    ]
